version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: spmbe
      MYSQL_USER: django_user
      MYSQL_PASSWORD: django_pass
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: mysql
    ports:
      - "8080:80"
    restart: always

  backend:
    build: .
    image: spme/spmbe_backend:latest
    container_name: backend
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=spmbe_backend.settings
      - DB_HOST=db
      - DB_NAME=spmbe
      - DB_USER=django_user
      - DB_PASSWORD=django_pass
      - DJANGO_DEBUG=False
    volumes:
      - ./spmbe_backend:/app
      - static_volume:/app/staticfiles
    expose:
      - "8000"
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - backend
    ports:
      - "80:80"
      - "8000:8000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - ./spme-fe/dist:/usr/share/nginx/html/frontend
    restart: unless-stopped

volumes:
  mysql_data:
  static_volume: